
-- create
CREATE TABLE EMPLOYEE (
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  SALARY  INTEGER NOT NULL,
  DEPT_ID INTEGER NOT NULL
);

CREATE TABLE DEPARTMENT (
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  LOCATION  TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (1, 'Candice', 4685, 1);
INSERT INTO EMPLOYEE VALUES (2, 'Julia', 2559, 2);
INSERT INTO EMPLOYEE VALUES (3, 'Bob', 4405, 4);
INSERT INTO EMPLOYEE VALUES (4, 'Scarlet', 2350, 1);
INSERT INTO EMPLOYEE VALUES (5, 'Ileana', 1151, 4);

INSERT INTO DEPARTMENT VALUES (1, 'Executive', 'Sydney');
INSERT INTO DEPARTMENT VALUES (2, 'Production', 'Sydney');
INSERT INTO DEPARTMENT VALUES (3, 'Resources', 'Cape Town');
INSERT INTO DEPARTMENT VALUES (4, 'Technical', 'Texas');
INSERT INTO DEPARTMENT VALUES (5, 'Management', 'Paris');




-- fetch 
SELECT d.name as department_name, COUNT(e.id) as employee_count
FROM DEPARTMENT as d
LEFT JOIN EMPLOYEE e ON d.id = e.dept_id
GROUP BY d.name
ORDER BY employee_count DESC, d.name ASC;
